services:
  nginx-1da60178:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www:delegated
    depends_on:
      - php-fpm-1da60178
    networks:
      - php-fpm-1da60178

  php-fpm-1da60178:
    build:
      context: .
      dockerfile: Dockerfile.prod.php
    restart: unless-stopped
    tty: true
    volumes:
      - .:/var/www:delegated
    networks:
      - php-fpm-1da60178

networks:
  php-fpm-1da60178:
    driver: bridge
